#!/bin/bash
export OSMOSISD_KEYRING_BACKEND=file

# Define the Python interpreter
PYTHON_INTERPRETER=/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11

# Source the config.py values
DENOM=$($PYTHON_INTERPRETER -c "import config; print(config.DENOM)")
UNIT_AMOUNT=$($PYTHON_INTERPRETER -c "import config; print(config.UNIT_AMOUNT)")
CONVERSION_RATE=$($PYTHON_INTERPRETER -c "import config; print(config.CONVERSION_RATE)")
KEY_NAME=$($PYTHON_INTERPRETER -c "import config; print(config.KEY_NAME)")
SNAPSHOTS_FOLDER=$($PYTHON_INTERPRETER -c "import config; print(config.SNAPSHOTS_FOLDER)")
FULL_DENOM=$($PYTHON_INTERPRETER -c "import config; denom=config.DENOM; print(next(key for key, value in config.TOKEN_NAME_MAPPING.items() if value == denom))")
DINGLEBERRY_FEE_AMOUNT="5000"  # Fee amount for dingleberry send (in microdenoms)
DINGLEBERRY_FEE_DENOM="uosmo"  # Denomination for the fee (usually 'uosmo' for Osmosis)

# Debug: Print config values
echo "DENOM: $DENOM"
echo "FULL_DENOM: $FULL_DENOM"
echo "UNIT_AMOUNT: $UNIT_AMOUNT"
echo "CONVERSION_RATE: $CONVERSION_RATE"
echo "KEY_NAME: $KEY_NAME"
echo "SNAPSHOTS_FOLDER: $SNAPSHOTS_FOLDER"
echo "DINGLEBERRY_FEE_AMOUNT: $DINGLEBERRY_FEE_AMOUNT"
echo "DINGLEBERRY_FEE_DENOM: $DINGLEBERRY_FEE_DENOM"

# Calculate the amount in micro units
AMOUNT=$($PYTHON_INTERPRETER -c "print(int($UNIT_AMOUNT * $CONVERSION_RATE))")

# Directories for transactions and balances
TRANSACTIONS_DIR="../data/transactions"
BALANCES_DIR="../data/balances"

# Create directories if they do not exist
mkdir -p $TRANSACTIONS_DIR
mkdir -p $BALANCES_DIR

# Create a dynamic balance file name
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
INITIAL_BALANCES_FILE="${BALANCES_DIR}/initial_balances_${TIMESTAMP}.json"
FINAL_BALANCES_FILE="${BALANCES_DIR}/final_balances_${TIMESTAMP}.json"

# Run get_wallet_balances.py first and store the initial balances
echo "Fetching initial wallet balances..."
$PYTHON_INTERPRETER get_wallet_balances.py $KEY_NAME --keyring-backend file --output $INITIAL_BALANCES_FILE

# Run print_double_dribble.py to display distributions
echo "Displaying distribution details..."
$PYTHON_INTERPRETER print_double_dribble.py

# Transaction generation
echo "Generating transaction data..."
PYTHON_SCRIPT_PATH="./generate_double_dribble.py"
FROM_ADDRESS=$(osmosisd keys show $KEY_NAME -a --keyring-backend file)

# Debug: Print from address
echo "FROM_ADDRESS: $FROM_ADDRESS"

# Run the Python script and capture the output
OUTPUT=$($PYTHON_INTERPRETER $PYTHON_SCRIPT_PATH --denom "$DENOM" --amount "$AMOUNT" --from-address "$FROM_ADDRESS")

# Print the entire output to debug
echo "Full output from Python script:"
echo "$OUTPUT"

# Extract JSON files generated by the Python script
TRANSACTION_FILES=$(echo "$OUTPUT" | grep -oP '(?<=saved: ).*\.json')

# Validate JSON files existence
if [ -z "$TRANSACTION_FILES" ]; then
    echo "No JSON transaction files found."
    exit 1
fi

echo "Generated JSON files:"
echo "$TRANSACTION_FILES"

# Parameters for the transaction
CHAIN_ID="osmosis-1"

for JSON_FILE in $TRANSACTION_FILES; do
    echo "Processing transaction file: $JSON_FILE"

    # Confirm if want to sign, and then sign
    read -p "Are you sure you want to sign the transaction? (y/n) " confirm_sign
    if [[ "$confirm_sign" == "y" || "$confirm_sign" == "Y" ]]; then
        SIGN_OUTPUT="${JSON_FILE%.json}_signed.json"
        echo "Signing the transaction using file: $JSON_FILE"

        # Sign the transaction
        osmosisd tx sign "$JSON_FILE" --from "$KEY_NAME" --chain-id "$CHAIN_ID" --keyring-backend file --output-document "$SIGN_OUTPUT"

        # Check if the signing was successful
        if [ $? -ne 0 ]; then
            echo "Error signing the transaction"
            exit 1
        fi
    else
        echo "Transaction signing cancelled."
        exit 0
    fi

    # Confirm if want to broadcast, and then broadcast
    read -p "You will broadcast this transaction, are you sure you want to proceed? (y/n) " confirm_broadcast
    if [[ "$confirm_broadcast" == "y" || "$confirm_broadcast" == "Y" ]]; then
        
        echo "Broadcasting the signed transaction..."
        osmosisd tx broadcast "$SIGN_OUTPUT"

        # Check if broadcast worked
        if [ $? -ne 0 ]; then
            echo "Error broadcasting the transaction"
            exit 1
        fi
    else
        echo "Transaction broadcasting cancelled."
        exit 0
    fi

    # Small delay between transactions
    echo "Waiting for 5 seconds before processing the next transaction..."
    sleep 5
done

# After 5 second countdown, run get_wallet_balances.py one last time and store the final balances
echo "Waiting for 5 seconds before fetching final wallet balances..."
sleep 5

# Fetch the final balances after the transactions
echo "Fetching final wallet balances..."
$PYTHON_INTERPRETER get_wallet_balances.py $KEY_NAME --keyring-backend file --output $FINAL_BALANCES_FILE

# Debug: Print initial and final balance file paths
echo "Initial Balances File: $INITIAL_BALANCES_FILE"
echo "Final Balances File: $FINAL_BALANCES_FILE"

# Calculate the balance differences
echo "Calculating balance differences for $DENOM..."

# Extract only the balance difference for the specific DENOM
BALANCE_DIFF=$($PYTHON_INTERPRETER calculate_balance_differences.py $INITIAL_BALANCES_FILE $FINAL_BALANCES_FILE | grep "$DENOM" | awk '{print $2}')

# Debug: Print the extracted balance difference for the specific denomination
echo "Extracted balance difference for $DENOM: $BALANCE_DIFF"

# Ensure BALANCE_DIFF is a valid number
if ! [[ $BALANCE_DIFF =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
    echo "Invalid balance difference: $BALANCE_DIFF"
    exit 1
fi

# Adjust the calculation: Subtract if positive, add if negative
if (( $(echo "$BALANCE_DIFF < 0" | bc -l) )); then
    # If balance difference is negative, add it to the amount
    AMOUNT_TO_SEND=$(echo "scale=2; 4932.84 + ($BALANCE_DIFF * -1)" | bc)
else
    # If balance difference is positive, subtract it from the amount
    AMOUNT_TO_SEND=$(echo "scale=2; 4932.84 - $BALANCE_DIFF" | bc)
fi

# Ensure BALANCE_DIFF is a valid number
if ! [[ $BALANCE_DIFF =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
    echo "Invalid balance difference: $BALANCE_DIFF"
    exit 1
fi

# Adjust the calculation: Just add the negative balance difference to the base amount
AMOUNT_TO_SEND=$(echo "scale=2; 4932.84 + $BALANCE_DIFF" | bc)

# Ensure AMOUNT_TO_SEND is a valid number
if ! [[ $AMOUNT_TO_SEND =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
    echo "Invalid amount to send: $AMOUNT_TO_SEND"
    exit 1
fi

# Convert to micro units
AMOUNT_TO_SEND_MICRO=$(echo "$AMOUNT_TO_SEND * 1000000 / 1" | bc)

# Debug: Print the amount to send in micro units
echo "Amount of dingleberries this time 🫐: $AMOUNT_TO_SEND"
echo ""
echo "~Debug~"
echo "Amount to send to dingleberry wallet in micro units: $AMOUNT_TO_SEND_MICRO"

# Send the remaining balance to the dingleberry wallet
DINGLEBERRY_WALLET_ADDRESS="osmo1gz7t9aaqwnmdhn5umm03rqqxd9spkjx3he4xkz"
if (( $(echo "$AMOUNT_TO_SEND > 0" | bc -l) )); then
    echo "Sending $AMOUNT_TO_SEND_MICRO micro$FULL_DENOM to the dingleberry wallet..."
    osmosisd tx bank send $FROM_ADDRESS $DINGLEBERRY_WALLET_ADDRESS $AMOUNT_TO_SEND_MICRO$FULL_DENOM --chain-id $CHAIN_ID --keyring-backend file --fees "$DINGLEBERRY_FEE_AMOUNT$DINGLEBERRY_FEE_DENOM"
else
    echo "No remaining balance to send to the dingleberry wallet."
fi