# simple calc
DINGLEBERRY_WALLET = "osmo1gz7t9aaqwnmdhn5umm03rqqxd9spkjx3he4xkz"
TOTAL_DISTRIBUTION = 4713.04
NUMBER_OF_NFTS = 2222
UNLISTED_NFTS = TOTAL_DISTRIBUTION / 2.22
LISTED_NFTS = NUMBER_OF_NFTS - UNLISTED_NFTS

DINGLEBERRIES = LISTED_NFTS * 2.22
print(DINGLEBERRIES)
