#!/bin/bash
export OSMOSISD_KEYRING_BACKEND=file

# Define the Python interpreter
PYTHON_INTERPRETER=/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11

# Source the config.py values
DENOM=$($PYTHON_INTERPRETER -c "import config; print(config.DENOM)")
KEY_NAME=$($PYTHON_INTERPRETER -c "import config; print(config.KEY_NAME)")

# Debug: Print config values
echo "DENOM: $DENOM"
echo "KEY_NAME: $KEY_NAME"

# Directories for transactions and balances
TRANSACTIONS_DIR="../data/transactions"
BALANCES_DIR="../data/balances"

# Create directories if they do not exist
mkdir -p $TRANSACTIONS_DIR
mkdir -p $BALANCES_DIR

# Create a dynamic balance file name
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
INITIAL_BALANCES_FILE="${BALANCES_DIR}/initial_balances_${TIMESTAMP}.json"
FINAL_BALANCES_FILE="${BALANCES_DIR}/final_balances_${TIMESTAMP}.json"

# Run get_wallet_balances.py first and store the initial balances
echo "Fetching initial wallet balances..."
$PYTHON_INTERPRETER get_wallet_balances.py $KEY_NAME --keyring-backend file --output $INITIAL_BALANCES_FILE

# Transaction generation using CSV file
echo "Generating transaction data from CSV..."
PYTHON_SCRIPT_PATH="./generate_transactions_from_csv.py"
FROM_ADDRESS=$(osmosisd keys show $KEY_NAME -a --keyring-backend file)

# Debug: Print from address
echo "FROM_ADDRESS: $FROM_ADDRESS"

# Run the Python script to generate transactions from CSV
OUTPUT=$($PYTHON_INTERPRETER $PYTHON_SCRIPT_PATH --csv "distribution.csv" --from-address "$FROM_ADDRESS" --denom "$DENOM")

# Print the entire output to debug
echo "Full output from Python script:"
echo "$OUTPUT"

# Extract JSON files generated by the Python script
TRANSACTION_FILES=$(echo "$OUTPUT" | grep -oP '(?<=saved: ).*\.json')

# Validate JSON files existence
if [ -z "$TRANSACTION_FILES" ]; then
    echo "No JSON transaction files found."
    exit 1
fi

echo "Generated JSON files:"
echo "$TRANSACTION_FILES"

CHAIN_ID="osmosis-1"

for JSON_FILE in $TRANSACTION_FILES; do
    echo "Processing transaction file: $JSON_FILE"

    # Confirm if want to sign, and then sign
    read -p "Are you sure you want to sign the transaction? (y/n) " confirm_sign
    if [[ "$confirm_sign" == "y" || "$confirm_sign" == "Y" ]]; then
        SIGN_OUTPUT="${JSON_FILE%.json}_signed.json"
        echo "Signing the transaction using file: $JSON_FILE"

        # Sign the transaction
        osmosisd tx sign "$JSON_FILE" --from "$KEY_NAME" --chain-id "$CHAIN_ID" --keyring-backend file --output-document "$SIGN_OUTPUT"

        # Check if the signing was successful
        if [ $? -ne 0 ]; then
            echo "Error signing the transaction"
            exit 1
        fi
    else
        echo "Transaction signing cancelled."
        exit 0
    fi

    # Confirm if want to broadcast, and then broadcast
    read -p "You will broadcast this transaction, are you sure you want to proceed? (y/n) " confirm_broadcast
    if [[ "$confirm_broadcast" == "y" || "$confirm_broadcast" == "Y" ]]; then

        echo "Broadcasting the signed transaction..."
        osmosisd tx broadcast "$SIGN_OUTPUT"

        # Check if broadcast worked
        if [ $? -ne 0 ]; then
            echo "Error broadcasting the transaction"
            exit 1
        fi
    else
        echo "Transaction broadcasting cancelled."
        exit 0
    fi

    # Small delay between transactions
    echo "Waiting for 5 seconds before processing the next transaction..."
    sleep 5
done

# After 5 second countdown, run get_wallet_balances.py one last time and store the final balances
echo "Waiting for 5 seconds before fetching final wallet balances..."
sleep 5

# Fetch the final balances after the transactions
echo "Fetching final wallet balances..."
$PYTHON_INTERPRETER get_wallet_balances.py $KEY_NAME --keyring-backend file --output $FINAL_BALANCES_FILE

# Debug: Print initial and final balance file paths
echo "Initial Balances File: $INITIAL_BALANCES_FILE"
echo "Final Balances File: $FINAL_BALANCES_FILE"

# Calculate the balance differences
echo "Calculating balance differences for $DENOM..."

# Calculate the balance difference using a Python script
$PYTHON_INTERPRETER calculate_balance_differences.py $INITIAL_BALANCES_FILE $FINAL_BALANCES_FILE
